### ISSUE TITLE
pay a second time？

### ISSUE THREAD

**Issue by 2677615279** [echodot-llc/Kubermagic#2]
I have paid 388 ¥ to purchase the commercial version of Red, but today I update the 1.7.2 version, and I cannot see my purchased information. You can only watch and pay 98 ¥ again.
Why do I have to pay a second time?

**Comment by scuml** [comment]
This is a bug that I will fix immediately.

**Comment by 2677615279** [comment]
I uninstalled and reinstalled Red, and I had to click to restore purchase every time I opened it, otherwise the window would pop up and the experience was very poor.
You should set that when the user reinstalls, he only needs to click once to restore the purchase, and the subsequent endless start-up pop-ups can be cancelled





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "echodot-llc/Kubermagic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [echodot-llc/Kubermagic] pay a second time？ (#2)





 
This is a bug that I will fix immediately.

**Comment by scuml** [comment]
I'll check into that.   Thanks for the suggestion. 

I have just submitted 1.7.3 to Apple which should fix the problem.  I apologize for the trouble it's caused.  

(Apple should have it approved in 7-8 hours)
